<?php

namespace App\Model;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($question){
            $question->slug = str_slug($question->title);
        });
    }

    protected $with = ['replies'];

    // This function will replace the default parameter ID for show route of API Resource , the new route should be .../slug
    public function getRouteKeyName()
    {
        return 'slug';
    }
    // This will exclude parameters in the request , by declare as [] we accept all
    //protected $guarded = [];

    protected $fillable = ['title','slug','body','user_id','category_id'];

    // Adding a custom attribute to model : https://laravel.com/docs/6.x/eloquent-serialization#appending-values-to-json
    public function getPathAttribute(){
        return "/question/$this->slug";
    }
    //
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class)->latest();
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }
}
